### ISSUE TITLE
Getting argument null exception on first run

### ISSUE THREAD

**Issue by szalapski** [jsakamoto/Toolbelt.AspNetCore.CssLiveReloader#3]
This didn't happen on my old PC but now it is on my new one.  Looks like something related to the file watcher?  Why can't it get a path? Any ideas?

```
watch : Started
Starting Planner.Server web host with appsettings.Developer.json...
Hosting environment: Developer
Content root path: c:\Planner\Server
Now listening on: https://localhost:5001
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
[2020-11-12 18:39:26 ERR] An unhandled exception has occurred while executing the request. System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.IO.File.GetLastWriteTimeUtc(String path)
   at Toolbelt.AspNetCore.CssLiveReloader.Internals.CssFileWatcherService.TryAddWatch(String url, Boolean timeStampCheck, DateTime timeStamp)
   at Toolbelt.AspNetCore.CssLiveReloader.Internals.CssWatchRequestHandler.InvokeAsync(HttpContext context, CssFileWatcherService cssFileWatcherService)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Toolbelt.AspNetCore.CssLiveReloader.Internals.InjectReloaderScriptMiddleware.InvokeAsync(HttpContext context)
   at Toolbelt.AspNetCore.CssLiveReloader.Internals.AddCssFileWatcherMiddleware.InvokeAsync(HttpContext context)
   at Westwind.AspNetCore.LiveReload.LiveReloadMiddleware.HandleHtmlInjection(HttpContext context) in C:\projects\Westwind.AspnetCore.LiveReload\Westwind.AspnetCore.LiveReload\LiveReloadMiddleware.cs:line 103
   at Westwind.AspNetCore.LiveReload.LiveReloadMiddleware.InvokeAsync(HttpContext context) in C:\projects\Westwind.AspnetCore.LiveReload\Westwind.AspnetCore.LiveReload\LiveReloadMiddleware.cs:line 72
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
`

**Comment by jsakamoto** [comment]
Thank you for reporting!

I also run into this exception myself this week, so I fixed it.

Could you try the latest version of this library?

- https://www.nuget.org/packages/Toolbelt.AspNetCore.CssLiveReloader/1.1.1

I hope the latest version of this library resolves this problem.

**Comment by szalapski** [comment]
Thanks very much for the quick response!  Yes, that works great.  Thanks
for a great library, it should be more popular.
